<a href="https://colab.research.google.com/github/asve06/act2_si_225_group2/blob/main/act2_si_eda_225_group2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Dataset loading, Exploration and Column Removal
**Student:** Jimmy Ochoa

### 1. Load the dataset using pandas library

In [20]:
import pandas as pd

In [21]:
df = pd.read_csv('reviews_most_relevant.csv')

### 2. Explore dataset

In [22]:
display(df.head())

,username,user_country,room_view,stay_duration,stay_type,review_post_date,review_title,rating,original_lang,review_text_liked,review_text_disliked,full_review,en_full_review,found_helpful,found_unhelpful,owner_resp_text
0,Butty,Canada,Deluxe Double Room with Balcony and Sea View,5 nights,Couple,02-03-2025 00:00:00,Beautiful gem of a hotel on a fabulous beach!,10.0,en-us,Beautiful boutique hotel right on the beach. M...,NaN,title: Beautiful gem of a hotel on a fabulous ...,title: Beautiful gem of a hotel on a fabulous ...,0,0,NaN
1,Jen,United States,Double Room with Two Beds,1 night,Family,09-19-2025 00:00:00,Relaxiing fun day trip,10.0,en-us,Always clean. Friendly staff. Safe family plac...,Nothing,title: Relaxiing fun day trip. liked: Always c...,title: Relaxiing fun day trip. liked: Always c...,0,0,Thank you very much for your comment. It is a ...
2,Santiago,Colombia,Budget Double Room,1 night,Solo traveller,09-18-2025 00:00:00,Exceptional,10.0,en-us,Todo genial,NaN,title: Exceptional. liked: Todo genial.,title: Exceptional. liked: Todo genial.,0,0,NaN
3,Ricardo,Colombia,Double Junior Suite with Sea View,2 nights,Couple,09-08-2025 00:00:00,The best hotel in town,9.0,en-us,"Really well located, the only hotel who has pr...",Everything on point,title: The best hotel in town. liked: Really w...,title: The best hotel in town. liked: Really w...,0,0,Thank you very much for your comment! We are d...
4,Sophia,United Kingdom,Double Room with Two Beds,3 nights,Family,09-03-2025 00:00:00,Very good,8.0,en,"Very nice staff, yummy breakfast, nice beach a...","Rooms near street are very loud, would be bett...","title: Very good. liked: Very nice staff, yumm...","title: Very good. liked: Very nice staff, yumm...",0,0,Thank you very much for sharing your experienc...

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1225 entries, 0 to 1224
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   username              1225 non-null   object
 1   user_country          1223 non-null   object
 2   room_view             1215 non-null   object
 3   stay_duration         1225 non-null   object
 4   stay_type             1225 non-null   object
 5   review_post_date      1225 non-null   object
 6   review_title          1225 non-null   object
 7   rating                1225 non-null   float64
 8   original_lang         1225 non-null   object
 9   review_text_liked     717 non-null    object
 10  review_text_disliked  460 non-null    object
 11  full_review           1225 non-null   object
 12  en_full_review        308 non-null    object
 13  found_helpful         1225 non-null   int64
 14  found_unhelpful       1225 non-null   int64
 15  owner_resp_text       114 non-null    object
dtypes: float64(1), int64(2), object(13)
memory usage: 153.3+ KB

In [24]:
df.describe()

            rating  found_helpful  found_unhelpful
count  1225.000000    1225.000000           1225.0
mean      9.344163       0.035918              0.0
std       1.037004       0.225824              0.0
min       1.000000       0.000000              0.0
25%       9.000000       0.000000              0.0
50%      10.000000       0.000000              0.0
75%      10.000000       0.000000              0.0
max      10.000000       3.000000              0.0

### 3. Drop columns that are not relevant

We decided to drop the columns **review_text_liked, review_text_disliked, full_review, and en_full_review**, as they either repeat information already present in **review_title** or merge data redundantly, adding no unique value. We also removed **found_helpful** and **found_unhelpful**, since they are always 0 and don't provide meaningful insight for analyzing guest satisfaction or trends. Additionally, **owner_resp_text** and **original_lang** were dropped as they are not relevant to understanding the guest experience. We kept **username, room_view, stay_duration, stay_type, review_post_date, review_title, rating**, and **user_country** to retain key contextual and demographic information that can help analyze trends and satisfaction patterns effectively.

In [25]:
columns_to_drop = ['review_text_liked', 'review_text_disliked', 'full_review', 'en_full_review', 'found_helpful', 'found_unhelpful', 'owner_resp_text', 'original_lang']
df.drop(columns = columns_to_drop, inplace= True)

In [26]:
df.head()

,username,user_country,room_view,stay_duration,stay_type,review_post_date,review_title,rating
0,Butty,Canada,Deluxe Double Room with Balcony and Sea View,5 nights,Couple,02-03-2025 00:00:00,Beautiful gem of a hotel on a fabulous beach!,10.0
1,Jen,United States,Double Room with Two Beds,1 night,Family,09-19-2025 00:00:00,Relaxiing fun day trip,10.0
2,Santiago,Colombia,Budget Double Room,1 night,Solo traveller,09-18-2025 00:00:00,Exceptional,10.0
3,Ricardo,Colombia,Double Junior Suite with Sea View,2 nights,Couple,09-08-2025 00:00:00,The best hotel in town,9.0
4,Sophia,United Kingdom,Double Room with Two Beds,3 nights,Family,09-03-2025 00:00:00,Very good,8.0

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1225 entries, 0 to 1224
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   username          1225 non-null   object
 1   user_country      1223 non-null   object
 2   room_view         1215 non-null   object
 3   stay_duration     1225 non-null   object
 4   stay_type         1225 non-null   object
 5   review_post_date  1225 non-null   object
 6   review_title      1225 non-null   object
 7   rating            1225 non-null   float64
dtypes: float64(1), object(7)
memory usage: 76.7+ KB

#Dataset cleaning and transformation
**Student:** Leynder Sánchez

### 4. Inconsistencies founded

In [28]:
# Finding possible duplicated data
df[df.duplicated(keep=False)]

,username,user_country,room_view,stay_duration,stay_type,review_post_date,review_title,rating
2,Santiago,Colombia,Budget Double Room,1 night,Solo traveller,09-18-2025 00:00:00,Exceptional,10.0
49,Matthew,Australia,Deluxe Double Room with Balcony and Sea View,4 nights,Couple,10-19-2024 00:00:00,Beautiful stay on the beach! Loved every moment,10.0
50,Matthew,Australia,Deluxe Double Room with Balcony and Sea View,4 nights,Couple,10-19-2024 00:00:00,Beautiful stay on the beach! Loved every moment,10.0
236,Sindy,Colombia,Budget Double Room,1 night,Couple,04-26-2025 00:00:00,Exceptional,10.0
237,Sindy,Colombia,Budget Double Room,1 night,Couple,04-26-2025 00:00:00,Exceptional,10.0
717,Santiago,Colombia,Budget Double Room,1 night,Solo traveller,09-18-2025 00:00:00,Exceptional,10.0
750,S,United States,Deluxe Double Room with Balcony and Sea View,14 nights,Solo traveller,12-10-2024 00:00:00,Superb,9.0
752,S,United States,Deluxe Double Room with Balcony and Sea View,14 nights,Solo traveller,12-10-2024 00:00:00,Superb,9.0

In [29]:
df.drop_duplicates(keep='first',inplace=True)
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [username, user_country, room_view, stay_duration, stay_type, review_post_date, review_title, rating]
Index: []

In [30]:
df[df['username'] == 'Anonymous']

,username,user_country,room_view,stay_duration,stay_type,review_post_date,review_title,rating
166,Anonymous,NaN,NaN,4 nights,Family,11-24-2023 00:00:00,Exceptional,10.0
167,Anonymous,United States,NaN,3 nights,Group,10-22-2022 00:00:00,you guys can put better effort on room decor a...,4.0
714,Anonymous,Ecuador,NaN,2 nights,Family,08-15-2025 00:00:00,Very good,8.0
715,Anonymous,Ecuador,NaN,1 night,Couple,05-28-2025 00:00:00,Superb,9.0
716,Anonymous,Ecuador,NaN,1 night,Couple,07-24-2023 00:00:00,Un espacio tranquilo y privado,10.0
855,Anonymous,Ecuador,NaN,1 night,Solo traveller,05-25-2025 00:00:00,Exceptional,10.0
856,Anonymous,Colombia,NaN,2 nights,Group,11-16-2023 00:00:00,Exceptional,10.0
1222,Anonymous,Ecuador,NaN,2 nights,Family,07-07-2025 00:00:00,Exceptional,10.0
1223,Anonymous,Netherlands,NaN,2 nights,Group,07-26-2023 00:00:00,Very good,8.0
1224,Anonymous,Ecuador,NaN,2 nights,Group,10-04-2022 00:00:00,Very good,8.0

We found duplicate rows with the same user and all information identical, for example Matthew or Sindy. Also, looking at the data, we noticed several 'Anonymous' users without a room view, which raises doubts about the truthfulness of the review.

### 5. Splitting of Review Date into Month and Year

In [31]:
df['review_post_date'] = pd.to_datetime(df['review_post_date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1221 entries, 0 to 1224
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   username          1221 non-null   object
 1   user_country      1219 non-null   object
 2   room_view         1211 non-null   object
 3   stay_duration     1221 non-null   object
 4   stay_type         1221 non-null   object
 5   review_post_date  1221 non-null   datetime64[ns]
 6   review_title      1221 non-null   object
 7   rating            1221 non-null   float64
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 85.9+ KB

In [32]:
df['month'] = df['review_post_date'].dt.month
df['year'] = df['review_post_date'].dt.year

In [33]:
df.head()

,username,user_country,room_view,stay_duration,stay_type,review_post_date,review_title,rating,month,year
0,Butty,Canada,Deluxe Double Room with Balcony and Sea View,5 nights,Couple,2025-02-03,Beautiful gem of a hotel on a fabulous beach!,10.0,2,2025
1,Jen,United States,Double Room with Two Beds,1 night,Family,2025-09-19,Relaxiing fun day trip,10.0,9,2025
2,Santiago,Colombia,Budget Double Room,1 night,Solo traveller,2025-09-18,Exceptional,10.0,9,2025
3,Ricardo,Colombia,Double Junior Suite with Sea View,2 nights,Couple,2025-09-08,The best hotel in town,9.0,9,2025
4,Sophia,United Kingdom,Double Room with Two Beds,3 nights,Family,2025-09-03,Very good,8.0,9,2025

### 6. Removal of Rows Containing Null Values

In [34]:
df.isnull().sum()

username             0
user_country         2
room_view           10
stay_duration        0
stay_type            0
review_post_date     0
review_title         0
rating               0
month                0
year                 0
dtype: int64

In [35]:
df.dropna(inplace=True)
df.isnull().sum()

username            0
user_country        0
room_view           0
stay_duration       0
stay_type           0
review_post_date    0
review_title        0
rating              0
month               0
year                0
dtype: int64

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1210 entries, 0 to 1221
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   username          1210 non-null   object
 1   user_country      1210 non-null   object
 2   room_view         1210 non-null   object
 3   stay_duration     1210 non-null   object
 4   stay_type         1210 non-null   object
 5   review_post_date  1210 non-null   datetime64[ns]
 6   review_title      1210 non-null   object
 7   rating            1210 non-null   float64
 8   month             1210 non-null   int32
 9   year              1210 non-null   int32
dtypes: datetime64[ns](1), float64(1), int32(2), object(6)
memory usage: 94.5+ KB

# Reviews by Month, Year & Country
**Student:** Ashley Vega

### 7. Distribution of Reviews

In [41]:
#Reviews per Month
df.groupby('month').size()

month
1      99
2     117
3     115
4     116
5      90
6      74
7      94
8     105
9      93
10    131
11     74
12    102
dtype: int64

In [40]:
#Reviews per Year
df.groupby('year').size()

year
2022    126
2023    434
2024    341
2025    309
dtype: int64

In [42]:
#Review by Country
df.groupby('user_country').size()

user_country
Abkhazia, ​Georgia          2
Argentina                  31
Australia                   7
Austria                     2
Belarus                     3
Belgium                    10
Bolivia                     2
Bosnia and Herzegovina      1
Brazil                     15
Canada                     42
Chile                      55
Colombia                   86
Costa Rica                  3
Czech Republic              4
Denmark                     1
Dominican Republic          2
Ecuador                   569
El Salvador                 7
Finland                     1
France                     17
Germany                    50
Hungary                     1
Iceland                     1
Ireland                     1
Israel                     12
Italy                      12
Jamaica                     1
Kuwait                      1
Kyrgyzstan                  1
Latvia                      1
Lithuania                   1
Mexico                      6
Netherlands                23
Panama                      1
Paraguay                    1
Peru                       12
Poland                      3
Portugal                    1
Puerto Rico                 2
Romania                     1
Russia                      2
Slovakia                    1
Slovenia                    4
South Korea                 1
Spain                      36
Sweden                      4
Switzerland                23
Turkey                      1
United Arab Emirates        1
United Kingdom             10
United States             129
Uruguay                     4
Venezuela                   1
Vietnam                     1
dtype: int64